### ISSUE TITLE
MGI transgene information is not available through mousemine

### ISSUE THREAD

**Issue by tomarashish** [mgijax/mousemine#13]
Hi @mgijax,

I am unable to fetch the MGI transgene information in mousemine web and through intermine api. The transgene information is present in the MGI web output. 
Can you please give some insight why is this happening?

**Comment by JoelRichardson** [comment]
Hi @tomarashish ,
Can you provide a little more detail? Which api call are you trying to use? What parameters? Etc?
Thanks!

**Comment by tomarashish** [comment]
Hi @mgijax,

Following are the details of my query:

API call to: service = Service("http://www.mousemine.org/mousemine/service")
```
query = service.new_query("Gene")
query.add_view("primaryIdentifier", "symbol","alleles.alleleType","alleles.primaryIdentifier")
query.add_constraint("symbol", "=", "EGFR", code = "A")
query.add_constraint("dataSets.name", "=", "Mouse Gene Catalog from MGI", code = "B")
```

Thanks

**Comment by JoelRichardson** [comment]
So, to paraphrase, you want the alleles (identifiers and types) for mouse Egfr? 
I'm confused because initially you said you were looking for transgenes, but Egfr is protein coding.
In any event, I was able to run your code with no issues. The query returned 19 rows. 
FYI, this includes the "wildtype" allele, which you might want to exclude by adding the constraint alleles.isWildType = false.

**Comment by JoelRichardson** [comment]
Sounds cool. Let me know if you have more questions.
